[package]
name = "broker"
version = "0.1.0"
authors = ["luben karavelov <luben@amazon.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
hyper = "0.12"
log = "0.4"
simple_logger = "1"
uuid = { version = "0.7", features = ["v4"] }
